site_name: Tudaiobrato's chaotic blog
site_url: https://taudaiobratno.github.io/chaoticmathblog/
theme:
    name: material 
site_author: Svetlana Orlova

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  
  
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
